### ISSUE TITLE
Cannot find ApexRefreshFile Command

### ISSUE THREAD

**Issue by tony534** [neowit/vim-force.com#47]
I cannot find :ApexRefreshFile command from command list, but I can find :ApexRreshProject command. How can I config vim to show :ApexRefreshFile ?

**Comment by neowit** [comment]
Current version of the documentation is misleading. 
When vim-force.com was `ant` based it included `:ApexRefreshFile`. Since the switch away from `ant` `:ApexRefreshFile` command has never been implemented. You are the first person who asked about it in two years, so I am guessing `:ApexRefreshFile` command is not very popular.

I may add `:ApexRefreshFile` back at some point in the future, if there is a compelling argument in favour of this.

For now (assuming you do not want to refresh the whole project for some reason) you have two options:  
1. use `:ApexDiffWithRemoteFile` - this will show you what's different between local and remote versions of the file in the current buffer, and you can pick all or some changes using your diff tool. You may also want to configure `'g:apex_diff_cmd'` if you have not done so already.  
2. Switch to `ant` based [version](https://github.com/neowit/vim-force.com/releases/tag/v1.2-with-ant) of the plugin - you will lose lots of functions, but `:ApexRefreshFile` will be there.

**Comment by tony534** [comment]
Thank you very much neowit!

You are doing an awesome project !

**Comment by nzchicken** [comment]
+1 to adding `:ApexRefreshFile` back. I must admit my use case is down to bad workflow... but yeah. I would mainly use it for VF Pages. I like to use the developer mode to create/edit some pages as it allows for instant preview. Sometimes I would like to make a very small minor change to the controller/extension (add a new field binding etc), and switching back to vim to make that change can be a pain. Assuming I wanted to then extend that controller/extension, it means I need to refresh the project. If I've got a lot of components, that's going to take extra time waiting for the whole project to refresh, when I know I only need one file refreshed.

Also in the rare case that I'm working with another person, they may edit the same file via their IDE (I'm slowly convincing others to switch to Vim-Force of course), and refreshing an entire project seems like a bit of overkill for just one file. If you added it back in, I'd definitely be happy, but I understand there are probably better things to work on.

**Comment by neowit** [comment]
Thanks for you comments @nzchicken and @tony534 . 
Will keep this issue open for now, to keep `:ApexRefreshFile` on my radar.

**Comment by neowit** [comment]
`:ApexRefreshFile` command is back in the latest version of the plugin.
