### ISSUE TITLE
Hang on awaiting connection

### ISSUE THREAD

**Issue by cobraextreme** [neowit/vim-force.com#77]
I've been using vim-force.com for years and love it, thanks!

I've recently updated to current from a pre-async version, and am having an issue with all of its commands not working now. All :ApexWhatever commands show 

    => Awaiting connection...
    Client connected from /127.0.0.1:40540

It waits until I kill it, at which time I see :

    received command:  --action=version --tempFolderPath='/home/me/.vim-force/temp' --config='/home/me/.vim-force/properties/myorg.properties' --projectPath='/home/me/dirname/myorg' --responseFilePath='/home/me/dirname/myorg/.vim-force.com/response_version' --pollWaitMillis=1000 --maxPollRequests=1000
    java.lang.NullPointerException
    Disconnect /127.0.0.1:40540

The one command that does work is :ApexValidateJavaConfig which reports "Config looks OK".

I have tried using newer versions of tooling jar (versions 0.3.6.6 and 0.3.8.0) with the same results. I am using Vim 8.0.

Do you have any suggestions of other things I can try?

**Comment by neowit** [comment]
There is a good chance that your vim version is not good.
Early (not native) vim builds with async job support had all sorts of problems on various OSes. 
In fact, even now, Windows version of GVim (80-069) available from vim.org does not work properly with jobs and channels.

Both messages (`Awaiting connection...` and `received command:...`) are is not supposed to be shown on vim side. Normally you can only observe these if you started server manually (from a console) then you would see server side messages like above in that console.

Try to make sure that you are using latest vim build. If that does not help then please report:
- OS/version
- is it gui or console vim ?
- vim version, ideally output of `:version` command
- `java -version` output

If you can record a short video demonstrating the problem that would be great.

> The one command that does work is :ApexValidateJavaConfig which reports "Config looks OK".

Your java config does indeed look OK because it was able to start the server (albeit channel stdout got screwed up).

**Comment by cobraextreme** [comment]
While looking into the above I have discovered that the problem occurs only if I am running vim in a tmux session -- I suspect the issue is not with vim-force.com at all, so I'm going to close this. Thanks for your help and for this great tool!
