### ISSUE TITLE
ApexRetrieve always looks in the first project directory

### ISSUE THREAD

**Issue by nzchicken** [neowit/vim-force.com#78]
When running `:ApexRetrieve` it looks like the first time it finds the current project from the open path.

If I start editing a file in another directory (different project), and run `ApexRetrieve` it still points to the old project, and only updates the first projects package.xml.

In order to get it to work on the new project, I have to close and reopen vim.

Let me know if you want me to clarify any of the above

**Comment by neowit** [comment]
It is a trade-off.

Current implementation supports only 1 `:ApexRetrieve` buffer per vim instance. 
In theory we could load that buffer from scratch every time when `:ApexRetrieve` is called, however, consider a scenario:

1. Call `:ApexRetrieve`
	- this loads metadata types related to current project

2. Work with `ApexRetrieve` buffer (e.g. select/expand)

3. Change to another project and call `:ApexRetrieve` there

Since we only have 1 `ApexRetrieve` buffer at this point we have to wipe content of existing ApexRetrieve and load it from scratch for new project (because metadata types may be different).
This way user loses whatever they did on step 2. above.

Having multiple `ApexRetrieve` buffers adds quite a bit of complexity and I am not sure if it is worth it.

I personally usually do `:bw` to leave `ApexRetrieve`. This ensures that next time I call `:ApexRetrieve` it will load this buffer from scratch.

Perhaps I should add a warning when user tries to call `:ApexRetrieve` while ApexRetrieve buffer already exists and loaded for another project/path.

What do you think?

**Comment by nzchicken** [comment]
Ah, I see why you did it that way. To be honest, I've used that funcitonality whilst in the same project and thought it was nice how it kept the old result.

I didn't know about the `:bw` trick, so I will just use that instead. I think 2 small changes would make it a bit easier:

1. Although the project path is displayed, maybe output the project name in the top section of the results of `:ApexRetrieve` to make it easier to see the current working project
2. The current comment refers to deleting a cached file - in addition add the `:bw` note as a shortcut for vim users, and mention that the buffer needs clearing if changing project

Let me know if you want me to attempt to add the above in (I'm useless at vimscript, and I know it should be as simple as edit a file, and output a variable - but i'm just that useless)
