### ISSUE TITLE
ApexTestCoverageShow return `No coverage data for MyClass.cls`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [neowit/vim-force.com#81]
But I have tests for this class.

**Comment by neowit** [comment]
as specified in `:help ApexTestCoverageShow` - you have to run `:ApexTestWithCoverage <method> <class-name>` prior to using `:ApexTestCoverageShow`
`:ApexTestWithCoverage` generates data used by `:ApexTestCoverageShow`

**Comment by vitaly-zdanevich** [comment]
I need to carefully read the documentation...

But correct syntax is

`:ApexTestWithCoverage tooling-async MyClass.MyMethod`

**Comment by vitaly-zdanevich** [comment]
I found that `:ApexTestCoverageShow` after `:ApexTestWithCoverage` return the same `No coverage data for MyClass.cls` but after switching to another buffer and back shows green vertical highlight for covered lines - but also not absolutely correct - my latest covered method do not highlighte.

**Comment by neowit** [comment]
If you get `No coverage data for MyClass.cls` this means that coverage data for that file is no longer available locally, unless you run appropriate test again.

> but after switching to another buffer and back shows green vertical highlight for covered lines

in most situations coverage highlight is shown until you turn it off for given file (or all files) explicitly. 
If you had coverage shown for some class then after running another test you have to toggle coverage off/on (e.g. with `:ApexTestCoverageToggle`) to see updated version, otherwise you will be seeing highlights related to last time when you called `:ApexTestCoverageToggle` or `:ApexTestCoverageShow`.
